RetireJS/retire.js

repository/npmrepository.json

False positive, as there is an option that is safe against recursion attack. Unfortunately it is not the default yet, but nonetheless only downstream libraries using it wrong should be considered insecure.

removed htmlparser2

---

repository/jsrepository.json

CVE value consistency #85 by replacing strings with single element lists

CVE value consistency #85

---

README.md

Adds information and an example gulp task (relates to #82)

Added Gulp task info

---

repository/npmrepository.json

also: fixes broken link to nodesecurity.io

fix: hubot-scripts package name typo

---

README.md

also slightly expand on what OWASP top 10 is.

fixed syntax

---

repository/npmrepository.json

see https://github.com/GitbookIO/gitbook/issues/1609. Also reported to @nodesecurity.

Add gitbook XSS vulnerability

---

repository/npmrepository.json

Revert #146

---

repository/npmrepository.json

Some issues did not follow the correct format.

Unified format across libraries

---

repository/jsrepository.json

Today version 0.8.9 of DOMPurify has been released which fixes the issues described at https://lists.ruhr-uni-bochum.de/pipermail/dompurify-security/2017-May/000006.html
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

Add DOMPurify < 0.8.9 security issues

---

repository/jsrepository.json

Adds identifiers to Bootstrap vulnerability added in #167

Add identifiers for bootstrap issue 20184

---

repository/jsrepository.json

More information: https://snyk.io/vuln/npm:jquery-ui:20160721

Included XSS in dialog closeText

---

repository/jsrepository.json
repository/npmrepository.json

Use https://github.com/angular/angular.js/blob/master/CHANGELOG.md#1230-patronal-resurrection-2016-07-21 instead of https://github.com/angular/angular.js/blob/master/CHANGELOG.md.

Add precise link to "usemap" issue in AngularJS.

---

repository/npmrepository.json

That link provides more info than the original one.
Also useful for deduping.

Reference fix/report PR for marked < 0.3.6 XSS

---

repository/npmrepository.json

Refs:
https://github.com/jquery/jquery/issues/3133#issuecomment-358923515
https://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2016-10707

Add missing information for jQuery CVE-2016-10707

---

repository/npmrepository.json

Refs: https://github.com/tschaub/grunt-gh-pages/commit/590f69767203d8c379fe18cded93bd5ad6cb53cb
Refs: https://github.com/tschaub/grunt-gh-pages/pull/41

Fix grunt-gh-pages affected version range

---

repository/npmrepository.json

v2.47.0-v2.51.0 are not affected, so split the entry in two.

Fix 'request' affected version range

---

repository/npmrepository.json

Hi,
Here's PR with latest disclosed reports from H1 program.
Also I fixed an error I did in previous PR (wrong issue category) - sorry about that :)
Regards,
bl4de
```
bl4de:~/hacking/contrib/retire.js/repository $ ./validate
106 regexes validated.
Success
```

HackerOne Node.js Ecosystem Bug Bounty Program - March 2018 disclosures

---

node/lib/retire.js

This loop seems unnecessary. Replacing it with a simple if-statement consistently reduced my run-time on a project from about 11.5 sec to about 10.5 sec.

Removed unneeded loop, speed improvements of about 10%

---

repository/npmrepository.json

Updates ```below``` versions for multiple packages

Fixes #224 - wrong "below" version numbers in multiple packages

---

repository/jsrepository.json

Added several missing CVEs.  Updated some NVD URLs to the new format.  Changed versioning for jPlayer vulnerabilities based on the vulnerability documentation, and added summaries.

Multiple JS repository updates. August 1, 2018

---

repository/npmrepository.json

Hi,
HackerOne Node ecosystem bug bounty program - vulnerabilities disclosed in August.
```
retire.js/repository $ ./validate
117 regexes validated.
Success
```
Cheers,
bl4de

HackerOne NodeJS Ecosystem Bug Bounty program - disclosed reports August 2018

---

repository/jsrepository.json

added CVE-2018-14040 and CVE-2018-14042
as well as some clarification for CVE-2018-14041

bootstrap: clearified vulnerabilities, added CVE's

---

repository/npmrepository.json

Hi,
HackerOne Node ecosystem bug bounty program - vulnerabilities disclosed in September.
Cheers,
bl4de
```
$ ./validate
119 regexes validated.
Success
```

HackerOne NodeJS Ecosystem Bug Bounty program - disclosed reports September 2018

---

repository/npmrepository.json

Hi,
Vulnerabilities from NodeJS Ecosystem bugbounty program disclosed in October.
```
$ ./validate
119 regexes validated.
Success
```
Cheers,
bl4de

HackerOne NodeJS Ecosystem Bug Bounty program - disclosed reports October 2018

---

repository/npmrepository.json

Per: https://github.com/dominictarr/event-stream/issues/116

Add event-stream's malicious package version

---

repository/jsrepository.json

Detect https://github.com/knockout/knockout/issues/1244

Added knockout (https://knockoutjs.com/)

---

repository/jsrepository.json

https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

Bootstrap 3.4.1 and 4.3.1

---

repository/npmrepository.json

Hi @eoftedal ,
There were not a lot of disclosed reports from January till March 2019, so here's PR with all of them together.
```
$ ./validate
121 regexes validated.
Success
```
Cheers,
bl4de

HackerOne NodeJS Ecosystem Bug Bounty program - disclosed reports Q1 2019

---

repository/jsrepository.json
repository/npmrepository.json

Add https://snyk.io/vuln/SNYK-JS-HANDLEBARS-173692 and https://snyk.io/vuln/SNYK-JS-HANDLEBARS-174183
Validates with `validate` script.
Did some formatting cleanup as well by mistake.

Add two Prototype Pollution vulns in Handlebars

---

repository/npmrepository.json

Added the eslint-utils, 'Arbitrary code execution' vulnerability to the list.
versions affected >=1.20 - <1.4.1

Added 'eslint-utils' vulnerability

---

index.html

so there are no security vulns on this site :-)

update jQuery and always load over HTTPS

---

repository/jsrepository.json
repository/npmrepository.json

https://nvd.nist.gov/vuln/detail/CVE-2020-7676

Add CVE-2020-7676 for angular < 1.8.0

---

node/lib/reporters/depcheck.js

Updated the depcheck format to be compatible with the https://jeremylong.github.io/DependencyCheck/dependency-check.2.3.xsd format used in https://github.com/dependency-check/dependency-check-sonar-plugin. 
On sonarqube it will look like this:

Updated depcheck format

---

chrome/js/background.js
chrome/js/popup.js

Additional error handling to help get rid of some console noise

Additional error handling

---

node/package.json

fix: pin colors to prevent dos in newer version

---

repository/jsrepository.json

jquery-ui vulnerabilities:
https://nvd.nist.gov/vuln/detail/CVE-2021-41184
https://nvd.nist.gov/vuln/detail/CVE-2021-41183
https://nvd.nist.gov/vuln/detail/CVE-2021-41182

Add missing jquery-ui CVEs

---

repository/npmrepository.json

Remove comma breaking json format

---

repository/jsrepository.json
repository/npmrepository.json

The CVE property must be an array.

Fix typo in CVE value for moment.js and bassmaster

---

repository/npmrepository.json

This is my first pull-request. I don't know if its completely correct.
I would like to see the following axios.js vulnerabilities:
- https://security.snyk.io/vuln/SNYK-JS-AXIOS-1579269
- https://security.snyk.io/vuln/SNYK-JS-AXIOS-1038255
- https://security.snyk.io/vuln/SNYK-JS-AXIOS-174505

Add axios.js vulns

---

repository/jsrepository.json

Fix axios typo

---

repository/jsrepository.json

Moment is a lightweight JavaScript date library for parsing, validating, manipulating, and formatting dates.
Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) via the preprocessRFC2822() function in from-string.js, when processing a very long crafted string (over 10k characters).

Update jsrepository.json for Momentjs CVE-2022-31129

---

repository/jsrepository.json

cross-site scripting vulnerability has been discovered affecting Iframe Dialog and Media Embed packages. The vulnerability may trigger a JavaScript code CVE-2023-28439

Added CKEditor Vulnerable version less than 4.21.0

---

node/lib/reporters/cyclonedx-json.js

Remove the "" results for duplicate components in cyclonedxJSON output.

---

node/README.md
node/src/cli.ts

**Comman** separated list -> **Comma** separated list

Fixed typo in README.md
