- .gitignore
- node/bin/retire
This issue: 
https://github.com/joyent/node/issues/3584 
leads to incomplete output from RetireJS when it's run on Windows and its output is piped to a different process (this is often the case when invoking RetireJS programmatically).
We can resolve the problem by checking for unflushed output prior to exiting, and waiting for the "drain" event before calling process.exit.
> Fix console.error process.exit flush issue

- node/bin/retire
You can use command line argument `--outputpath <file>` to route all the output to the file specified. Currently, it will overwrite the file if it exists and will fail without running any scan if the file can't be opened for writing.
One feature I didn't add, but we might want to consider is the ability to route vulnerabilities to one file and the rest of the output to another. Adding it wouldn't be all that difficult, but unless it's something people are actually going to use, I'll hold off on it for now.
> Add support for output to file

- firefox/lib/repo.js
- node/bin/retire
Swap from raw.github.com to raw.githubusercontent.com, as per https://developer.github.com/changes/2014-04-25-user-content-security/
> Update URLs for loading repository data from GitHub

- node/bin/retire
PR #91 made exit() only get called if the output format is JSON, which means if you're using this in the default text format, the exit code will always be 0, even if you have vulnerabilities.
> Call exit() even if not using JSON output

- node/bin/retire
Fixed `--exitwith` flag on Node retire.js app to accept an interger as the exit code otherwise `config.exitwith` would return `true` when any value was provided.
>  Fixed --exitwith option to accept an interger as the exit code

- repository/jsrepository.json
Change the jquery version extractor to more exactly recognize the format of jQuery versions.  The avoids recognizing jqLite as jQuery and marking the latest version of jqLite as a old vulnerable version of jQuery.
Fixes bug https://github.com/RetireJS/retire.js/issues/108
> Make jquery version extraction more specific

- firefox/package.json
- fx.sh
Since firefox 38 cfx is replaced with jpm and hence some customization is required in firefox extension too
https://blog.mozilla.org/addons/2015/02/26/jpm-replaces-cfx-for-firefox-38/
atleast the xpi is compiling and installing partially fixes #106 
but the plugin still needs to be tested for its usage.
> added jpm and firefox 38 support

- node/package.json
I did a quick `ack '_[.(]'` to see if the upgrade would cause any
trouble, but seeing that only `extend`, `pick`, `map`, `flatten` and
`detect` are being used, it seemed save to allow `1.8.x` as well.
Useful link: http://underscorejs.org/#changelog
> Updated underscore dependency.

- repository/jsrepository.json
YUI v2.x branches use "YAHOO.VERSION" to expose version information, added support for this.
> Added support for extracting version info of YUI v2.x branches.

- node/bin/retire
- repository/jsrepository.json
This patch adds the ability to specify a different URL to download the jsrepository and npmrepository from for cases where the user might have an internal host where the repositories are cached.
> Added ability to download repos from internal URL

- repository/npmrepository.json
The original incorrect reference was to a mapbox.js security issue.
> is-my-json-valid is pointing to the wrong security advisory

- repository/jsrepository.json
Link to details here: http://www.cvedetails.com/cve/CVE-2013-4940/
The issue didn't exist before 3.0.0 as the affected flash file io.swf didn't exist prior.
> Add missing atOrAbove condition to CVE-2013-4940.

- index.html
Added link to grunt-retire making it easier to find.
Started linking all the different ways to use retirejs, but got unsure if we should link to all the different subdirectories in the retirejs repo etc. So opted to not linking the list, but just adding a link in the grunt-retire section.
> Update index.html with link to grunt-retire

- node/lib/retire.js
The version regex which is generated is greedy, so in cases where the filename extractor contains an optional min (retire-example-(§§version§§)(.min)?\\.js), the ".min" becomes part of the matched version. Because of the way isAtOrAbove works, this hasn't been an issue in the past, but .min should not be part of the version number.
> Made version regex reluctant

- repository/jsrepository.json
They decided to change their domain and URL structure without redirecting users of the old URL to the new one.
> Fix broken sourceclear links

- node/lib/retire.js
This is a fix to issue https://github.com/RetireJS/retire.js/issues/141
> Handle vulnerability definitions without "below" property

- repository/npmrepository.json
The vulnerability has been fixed in commit https://github.com/node-js-libs/cli/commit/fd6bc4d2a901aabe0bb6067fbcc14a4fe3faa8b9 and included in the release v1.0.0 of cli already
> Define “below” version for “cli” (1.0.0)

- node/lib/repo.js
Check if the cache file exists, if not don't try to delete it since that will throw an error. 
It can be removed by some other process or exception.
> Check if cache file exists before removing it.

- repository/jsrepository.json
DOMPurify below 0.8.6 is vulnerable to a XSS vulnerability in Safari 10.1 and 10.2.
Ref https://github.com/cure53/DOMPurify/releases/tag/0.8.6
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
> Add check for DOMPurify < 0.8.6

- repository/jsrepository.json
The current link for this vulnerability is not very helpful. I have added another link which provides some more useful information.
> Add additional link for prototype.js vulnerability

- repository/npmrepository.json
This fixes a previous commit that had used "atOrAfter" in place of "atOrAbove" for several vulnerabilities.
It also corrects the vulnerability range for "gomeplus-h5-proxy".
> Fix incorrect npm repository JSON attributes

- repository/jsrepository.json
Old links no longer work. This was the best I could find for an updated reference.
> Fixed link for SWFObject

- repository/npmrepository.json
I have added the new critical electron vulnerability.
See https://nodesecurity.io/advisories/563 and https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1000006
> CVE-2018-1000006: added electron vulnerability

- node/lib/resolve.js
This fixes a runtime error (TypeError: Cannot convert undefined or null to object) when running retire on a project where there is no  dependencies key in the package.json.
> Allow no dependencies key in package.json

- repository/jsrepository.json
https://nvd.nist.gov/vuln/detail/CVE-2015-9251
> jQuery before 3.0.0 is vulnerable to Cross-site Scripting (XSS) attacks when a cross-domain Ajax request is performed without the dataType option, causing text/javascript responses to be executed.
> Reference CVE-2015-9251 for jquery bug 2432

- repository/npmrepository.json
atOrAbove was missing, the first (and only) affected version was 5.1.1
Also, the summary was incorrect.
Refs: https://nodesecurity.io/advisories/81
Refs: https://github.com/dwyl/hapi-auth-jwt2/issues/111
> Fix hapi-auth-jwt2 affected range and summary

- repository/jsrepository.json
The identifier references the incorrect CVE
> Fixed incorrect CVE reference

- node/lib/repo.js
When multiple instances of retire are run concurrently, in separate processes, `fs.existsSync` will sometimes return true but then `fs.unlinkSync` will result in an `ENOENT` "no such file or directory" error. Rather than check for the existence of the file, I'm just attempting to delete it and ignoring any `ENOENT` errors.
Closes #235
> Ensuring concurrently running instances of retire don't break

- repository/npmrepository.json
Hi,
HackerOne Node ecosystem bug bounty program - vulnerabilities disclosed in May.
As mentioned in https://github.com/RetireJS/retire.js/issues/224#issuecomment-391127649, I've used `99.999.99999` as a `below` version number for packages without fix applied.
`validate` output:
```
$ ./validate
107 regexes validated.
Success
```
Regards,
bl4de
> HackerOne NodeJS Ecosystem Bug Bounty program - disclosed reports May 2018

- README.md
Remove the deprecated gulp-util package from the gulp task example and replace with non-deprecated packages.
> gulp-util is deprecated

- repository/jsrepository.json
The prior regex did not match versions 3.* to at least 4.3.*.
E.g. in 3.5.10 the marker `tinyMCEPreInit` comes after `majorVersion:"3",minorVersion:"5.10"`.
See [here](http://archive.tinymce.com/download/older.php) for older versions of tinyMCE.
> Add replace regex to match older versions of tinyMCE

- repository/npmrepository.json
Merge has fixed the prototype pollution vulnerability: 
https://github.com/yeikos/js.merge/compare/v1.2.0...master
> Allow merge 1.2.1

- repository/npmrepository.json
Hi,
HackerOne NodeJS Ecosystem Bug Bounty program - reports disclosed in November.
```
$ ./validate
119 regexes validated.
Success
```
Cheers,
bl4de
> HackerOne NodeJS Ecosystem Bug Bounty program - disclosed reports November 2018

- repository/npmrepository.json
The authors of `protobufjs` back-ported the security fix from 6.8.6 into the 5.x branch at 5.0.3.  Updating the `npmrepository` file so it treats the 6.x and 5.x versions separately so the reporting comes out correctly.
This is related to issue https://github.com/RetireJS/retire.js/issues/275
> Updated ProtobufJS Versions

- repository/npmrepository.json
The original issue created for the hackerone report and linked PR for the fix: https://github.com/brianloveswords/base64url/issues/24
Also see the npm security advisory has the updated version range: https://www.npmjs.com/advisories/658
Looking at the repo there isn't a tag for the 3.0.0 release so it's not guaranteed that the fix was actually  deployed until the 3.0.1 release so I set that as the minimum version.
> repository update: base64url vulnerability is patched in later versions

- repository/npmrepository.json
- CVE-2018-3752 was fixed in merge-options in 1.0.1, see:
-- https://github.com/schnittstabil/merge-options/issues/10
-- https://github.com/schnittstabil/merge-options/issues/8
> Fixed wrong version number for npm module "merge-options"

- repository/npmrepository.json
Hi,
Reports disclosed in December 2018.
```
$ ./validate
119 regexes validated.
Success
```
There are only two reports disclosed in December.
Looks like the program has lost its popularity, also does not accept new submissions more often now :/
I know people from NodeJS Security Working Group had issues with members wiling to triage, validate and handle reports on HackerOne, also there is npm Responsible Disclosure program running.
Anyway, I will keep posting PRs with disclosed reports as long as they will appear.
Regards,
bl4de
> HackerOne NodeJS Ecosystem Bug Bounty program - disclosed reports December 2018

- repository/jsrepository.json
The DOS in $Sanitize vulnerability for angularjs versions below 1.6.3 gives a link where it is pretty hard to find information on the exact vulnerability.
I found the specific issue and added a link so the next person with that needs it will have an easier time.
> Add more descriptive link for angularjs vulnerability

- repository/jsrepository.json
This PR is to capture the recently fixed (in 3.4.0) vulnerability in JQuery, a prototype pollution one. it is considered a minor as it's quite difficult to exploit.
> Added jquery vulnerability as per CVE-2019-11358

- node/lib/reporters/json.js
The issue I have is
```gherkin
When running a retire with json and output path
Then errors are not published to the final object, thus in the result
```
Errors and warnings reported with `exitWithError()` don't have results context, and storing data inside the logger object instead. Have a look at the code below, this is what happens
```
var obj = {}
var arr = []
obj.push = arr.push
obj.push(1)
console.log(arr)
console.log(obj)
```
> Fix json reporter exitWithError

- repository/jsrepository.json
BootstrapCDN expose bootstrap js at '../bootstrap/_version_/**js**/bootstrap(.min).js' link, but existing uri extractor regex doesn't handle the **js** part. Note, that some old bootstrap libs don't have the version label in the content (e.g. http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js), so retire.js misses such findings.
This PR adds the uri regex that supports uri form exposed by CDNs.
> Added popular bootstrap's uri extractor

- simpleserver.py
Adds the ability with simple server to change the port as well support both python 2 and 3.
Simple but perhaps useful.
Enjoy! :smile:
> simpleserver port argument with python 2 and 3 support

- node/README.md
- node/bin/retire
- node/lib/repo.js
This MR adds two new options to the commandline scanner:
1. `--insecure` - Enable fetching remote jsrepo/noderepo files from hosts using an insecure or self-signed SSL (TLS) certificate
1. `--cacert <path>` - Use the specified certificate file to verify the peer used for fetching remote jsrepo/noderepo files
> Support insecure or self-signed SSL certs

- README.md
Note that this builds on the add-on previously mentioned - that add-on was a PoC and is superseded by the official add-on.
> Added details of the 'official' ZAP add-on

- repository/jsrepository.json
One of the tinyMCE vulnerabilities added with 1b86c859bcd7723fc99ba64d782d3434434c6bcc matches an incorrect version. The correct version should be `5.2.2`, as linked in the info of that vulnerability.
> Fixed incorrect tinyMCE vuln version

- repository/jsrepository.json
I have encountered the case where the bootstrap.min.js was bundled with some other libs with comments removed (so the version couldn't be grabbed from there). But looking inside some 3.x.x versions of bootstrap's .min.js versions occurrences can be found:
```
d=function(b){a(b).on("click",c,this.close)};d.VERSION="3.2.0",d.prototype.close=function(b){function c()
d=function(b){a(b).on("click",c,this.close)};d.VERSION="3.3.0",d.TRANSITION_DURATION=150,d.prototype.close=function(b)
a=function(t){s(t).on("click",e,this.close)};a.VERSION="3.4.0",a.TRANSITION_DURATION=150,a.prototype.close=function(t)
d=function(b){a(b).on("click",c,this.close)};d.VERSION="3.3.7",d.TRANSITION_DURATION=150,d.prototype.close=function(b)
```
I'm proposing an additional, contextual filecontent extractor that …
> Additional Bootstrap's filecontent extractor

- node/lib/resolve.js
This checks that the underlying file exists before trying to resolve the real path.
Fixes #342
> Symlink with non-existent file caused uncaught exception

- chrome/js/background.js
- chrome/js/content.js
trying to squash chrome error on extension page addressing https://github.com/RetireJS/retire.js/issues/350
> Move chrome logging from warn to log to squash plugin errors in the chrome extension manager page

- repository/jsrepository.json
In some cases `prettyPhoto` and `jPlayer` RegExp extractors lead to denial of service - node's process just stops responding.
Example:
```js
/**
* @return {string}
*/
function generateTestStr() {
let size = 20e6;
let bodyStr = '';
while (bodyStr.length < size) {
bodyStr += '"/* dksjfsdkjf sdsd sd sd  */ abc",'
}
let str = [
'/*! For license information please see LICENSE.txt */',
bodyStr,
'//# sourceMappingURL=vendors.js'
].join('\n');
return str;
}
async function run() {
// note: `§§version§§` -> `[0-9][0-9.a-z_\-]+`
const rxCases = [
// new expressions - fast execution
/\/\*[\r\n -]+Class: prettyPhoto(?:.*\n){1,3}[ ]*Version: ([0-9][0-9.a-z_\-]+)/,
/\/\*!?[\n *]+jPlayer Plugin for jQuery (?:.*\n){1,10}[ *]+Version: ([0-9][0-9.a-z_\-]+)/,
// old expressions - DoS …
```
> Fix DoS-prone extractors for prettyPhoto and jPlayer

- repository/jsrepository.json
I was not able to provide the following extractors:
- markdown-it (func)
- jszip (filename, filecontent and func)
> Add vulns markdown-it.js & jszip.js

- repository/jsrepository.json
This adds CVE-2022-31160 for jquery-ui < 1.13.2 (https://github.com/jquery/jquery-ui/security/advisories/GHSA-h6gj-6jjq-h8g9).
> Adds jquery-ui CVE-2022-31160

- repository/jsrepository.json
Commmit 0a61d8bbb7483e972c4bb07f4cdd3e0963f452d8 ("Update next.js vuln") creates a new vulnerability entry where the "info" field is missing. This is causing downstream issues as such field is requested by some libraries using the feeed. This commit add the missing field with the correct value.
> Update next.js vuln: added required 'info' attribute

- repository/jsrepository-master.json
- repository/jsrepository.json
- repository/testcases.json
retire.js is not currently recognising AngularJS 1.8.0 and potentially other versions. 
The first filecontent regular expression is as follows: `/\*[ \n]+AngularJS v(§§version§§)`
This matches https://code.angularjs.org/1.8.0/angular.min.js because the comment at the top of the file is
```
/*
AngularJS v1.8.0
(c) 2010-2020 Google, Inc. http://angularjs.org
License: MIT
*/
```
However, https://code.angularjs.org/1.8.0/angular.js has a header of
```
/**
* @license AngularJS v1.8.0
* (c) 2010-2020 Google, Inc. http://angularjs.org
* License: MIT
*/
```
Which does not match against the current implementation of the regex. This PR adds an optional non-capturing group of "@license " as a prefix to cover this case.
> Extend AngularJS filecontent regex to match contents of 1.8.0 AngularJS

- repository/jsrepository-master.json
- repository/jsrepository-v2.json
- repository/jsrepository-v3.json
- repository/jsrepository.json
Generic pattern with the npm style co-ordinates seems unnecessary for detection as the test cases all pass without this pattern included.
Ran all the tests prior, and also experimented with some other versions just in case. Didn't add them to the test list, as all seems OK and similar to current structures.
> Fixes #440 - Reduce chance of false positives for pdf.js

- repository/jsrepository-master.json
- repository/jsrepository-v2.json
- repository/jsrepository-v3.json
- repository/jsrepository.json
The current URL redirects to the root of the blog (the page mentionned probably doesn't exist anymore), try to replace it by one mentioning AngularJS being EOL
> docs: Update angular js deprecation URL

- chrome/build/package.json
This will fix Issue #445 
since npm handles the paths for node_modules/.bin
it will automatically use the correct binary from node_modules/.bin.
> fix build command : add browserify directly instead of looking in node_modules/.bin

- LICENSE.md
The Apache-2.0 license is applied by putting the full text of the license into LICENSE and putting the header text (which is currently in the LICENSE file) into each code file's top comment area--per https://www.apache.org/legal/apply-license.html#new
This at least starts that fix. 😁
This should also help robots properly tag this repo as Apache-2.0 licensed.
❤️ 🎩
> Update LICENSE.md with full Apache-2.0 text
